### ISSUE TITLE
Need courier.postProfile() method need

### ISSUE THREAD

**Issue by maaariii** [trycourier/courier-node#108]
## Steps to Reproduce the Problem

**Need method,**
import { CourierClient } from "@trycourier/courier";

const courier = CourierClient({ authorizationToken: "<AUTH_TOKEN>" });
  courier.postProfile()
 

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by tk26** [comment]
@maaariii `mergeProfile()` method is intended to do this - please let us know if this helps!
