### ISSUE TITLE
This is more of an improvement, is it possible to insert hyperlinks ( just like anchor tag in html ) in the message body to redirect to a url.

### ISSUE THREAD

**Issue by ppreetii** [trycourier/courier-node#109]
## Expected Behavior
I tried to use direct html code, and read the documentation examples, but couldn't find anything like that. Maybe you could help out.

## Actual Behavior
Not able to embed links in message body.

## Steps to Reproduce the Problem
Example Code :
return courier.send({
        message: {
          content: {
            title: "Password Reset",
            body: 
             ` We received a request to change password for this account.Click this 
              <link> to reset your password.`      
          },
          to: {
            email: <emailId>
          }
        }
      });

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by tk26** [comment]
Hey @ppreetii - here's an example for sending html as an element via Courier Elemental -

```
const { requestId } = await courier.send({
      message: {
        to: {
          email: "your-email-here"
        },
		content: {
		  elements: [{
			type: "channel", 
			channel: "email", 
			raw: {
		      html: "your-html-here"
			}
		  }],
		  version: "2022-01-01"
		}
      });
```

Let us know if this helps and/or if you have any questions!
