### ISSUE TITLE
Type signature not matching server expected response

### ISSUE THREAD

**Issue by toddheslin** [trycourier/courier-node#140]
## Expected Behavior
Typescipt doesn't complain for the correct server payload

## Actual Behavior
The example in the repo show passing in an object with an accounts property:
https://github.com/trycourier/courier-node/blob/041a2043c4af08ccb8fb5d56bac8f97d23248b14/README.md?plain=1#L837-L843

However, this creates a type error:
```
Argument of type '{ accounts: { account_id: string; profile: {}; }[]; }' is not assignable to parameter of type 'IUserAccount[]'.
  Object literal may only specify known properties, and 'accounts' does not exist in type 'IUserAccount[]'.
```

But this response actually works.

If we keep typescript happy with:
```ts
await courier.users.putAccounts("<USER_ID>",  [
  { account_id: "ACCOUNT_ID", profile: { foo: "bar" } }
]);
```

We get a 400 error with: ` { message: 'must be object', type: 'invalid_request_error' }`

## Steps to Reproduce the Problem

  1. Follow the docs example
  2. Observe the type error
  3. Make typescript happy
  4. Observe the 400 server error

## Specifications

  - Version: 5.0
  - Platform: node18
  - Subsystem: macos

**Comment by dsinghvi** [comment]
@toddheslin this should be fixed in version 6.x!
