### ISSUE TITLE
Documentation update needed for courier.issueToken 

### ISSUE THREAD

**Issue by charlesverge** [trycourier/courier-node#162]
**Description**

The location of the issueToken function appears to been updated and there is no documentation or example of its new location.

**Comment by dsinghvi** [comment]
@charlesverge we're going to update the README tomorrow, I'll ping this thread with an update. Till then feel free to use `v5.7.0`!

**Comment by charlesverge** [comment]
Well that was a fast response!

**Comment by dsinghvi** [comment]
@charlesverge you should be able to use `v6.0.2` of the SDK -- `courier.authTokens.issueToken(...)` is the method.

**Comment by dsinghvi** [comment]
Closing this issue since this is now supported, let me know if you hit any issues @charlesverge

**Comment by charlesverge** [comment]
@dsinghvi The issue was about documentation, currently I don't see any updates where made to document this function in the README.md and new users will end up using their server key to create profiles rather then the token from issueToken.
