### ISSUE TITLE
Property `slack` is missing in `MessageRecipient`

### ISSUE THREAD

**Issue by NatoBoram** [trycourier/courier-node#176]
Say I want to send a message to Slack. This is the format I found at <https://www.courier.com/docs/platform/channels/direct-message/slack/#sending-to-a-public-or-private-channel>.
```ts
import { CourierClient } from "@trycourier/courier"

const courier = new CourierClient({ authorizationToken: "courier_auth_token" })

await courier.send({
	message: {
		to: {
			slack: { access_token: "slack_access_token", channel: "channel_id" },
		},
		data: { message: "this is a message" },
	},
})
```
The project doesn't pass sanity checks because `MessageRecipient` doesn't contain `slack`
```ts
src/courier/slack.ts:8:4 - error TS2353: Object literal may only specify known properties, and 'slack' does not exist in type 'MessageRecipient'.

8    slack: { access_token: "slack_access_token", channel: "channel_id" },
     ~~~~~

  node_modules/@trycourier/courier/api/resources/send/types/ContentMessage.d.ts:16:5
    16     to: Courier.MessageRecipient;
           ~~
    The expected type comes from property 'to' which is declared here on type 'Message'


Found 1 error in src/courier/slack.ts:8
```

**Comment by dsinghvi** [comment]
Hey @NatoBoram thanks for filing this issue. For context, Courier's SDK is generated with automation so this will involve updaating their API Definition and regenerating the SDK. We should be able to get to this today!

**Comment by tk26** [comment]
@NatoBoram cc @bwebs @dsinghvi this should be live with the latest release - please let us know if you have any questions/feedback :)

**Comment by NatoBoram** [comment]
I just updated to `@trycourier/courier@6.0.6`, reset my node_modules and lockfiles and restarted my CLIs but it doesn't seem to have changed anything
```ts
import { CourierClient } from "@trycourier/courier"

const courier = new CourierClient({ authorizationToken: "courier_auth_token" })

await courier.send({
	message: {
		to: {
			slack: { access_token: "slack_access_token", channel: "channel_id" },
		},
		data: { message: "this is a message" },
	},
})
```
```ts
src/courier/slack.ts:8:4 - error TS2353: Object literal may only specify known properties, and 'slack' does not exist in type 'MessageRecipient'.

8    slack: { access_token: "slack_access_token", channel: "channel_id" },
     ~~~~~

  node_modules/@trycourier/courier/api/resources/send/types/ContentMessage.d.ts:16:5
    16     to: Courier.MessageRecipient;
           ~~
    The expected type comes from property 'to' which is declared here on type 'Message'


Found 1 error in src/courier/slack.ts:8
```

**Comment by bwebs** [comment]
I think I spotted it. We are re-using this type in a couple of places, but it looks like we missed the "slack" property in Recipient that already existed in UserProfile. We tested with UserProfile, hence the miss.

**Comment by bwebs** [comment]
v6.0.7 will be released shortly; tested the typing for `courier.send({to:{slack: ...}})` upstream as well.
