### ISSUE TITLE
Support for Cloudflare Workers

### ISSUE THREAD

**Issue by 0x62** [trycourier/courier-node#66]
## Expected Behavior
Builds successfully.

## Actual Behavior
Fails.

## Steps to Reproduce the Problem
Install on an application running on Cloudflare Workers.

This library fails as it relies on XHR/Axios under the hood, which Cloudflare Workers don't support. My suggestion would be to change requests to use `fetch`, and provide a configuration option when initialising to supply your own instance of `fetch`. This could then be used with `cross-fetch` to support pure Node environments and the 'webworker-ish' environment of CF workers with the same codebase.

This isn't preventing me using it (just wrote my own API wrapper), but it would be nice to have.

**Comment by vahnag** [comment]
@0x62 we just released v4.0.0 version of this package with a rewrite under the hood to use `fetch` instead of `axios` which will allow it to be used in Workers as well as node environments.
