### ISSUE TITLE
Add some examples in ReadMe for enhanced send api

### ISSUE THREAD

**Issue by NmSand** [trycourier/courier-node#75]
## Expected Behavior

A consumer of the lib should be able to see some usage/examples for the enhanced send API

## Actual Behavior

No enhanced send usage/examples makes it a pain to try the sdk out.

**Comment by suhasdeshpande** [comment]
<img src="https://media4.giphy.com/media/3NtY188QaxDdC/giphy.gif"/>

**Comment by tk26** [comment]
looks like we have a bunch of examples now :) Feel free to open a PR @NmSand if we need more!
