### ISSUE TITLE
Support types for the "new" send step in the invoke automations API

### ISSUE THREAD

**Issue by manurana** [trycourier/courier-node#98]
## Expected Behavior
According to the [docs](https://www.courier.com/docs/automations/steps/#send), the "new" send step in Automations accepts two properties, "action" and "message". So an attempt to use the "message" property should not throw a typescript error.

## Actual Behavior
A typescript error is seen.  
`Object literal may only specify known properties, and 'message' does not exist in type 'IAutomationSendStep'`
Call completes SUCCESSFULLY, and the automation + email send are successful

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1749522/175515372-312ff9e7-ddc5-4638-9be7-f6d67b04f3ac.png">

## code sample

```javascript
import { CourierClient } from "@trycourier/courier";

const courier = CourierClient({
  authorizationToken: "pk_test_XXXXXXX",
});

const doAutomation = async () => {
  const { runId } = await courier.automations.invokeAdHocAutomation({
    automation: {
      cancelation_token: "I_AM_TOKEN",
      steps: [
        {
          action: "send",
          message: {
            to: {
              data: {
                name: "Manu Rana",
                user_id: "123",
              },
              email: "m@t.com",
            },

            content: {
              title: "Back to the Future II",
              body: "Oh my {{name}}, we need 1.21 Gigawatts!",
            },

            routing: {
              method: "single",
              channels: ["email"],
            },
          },
        },
      ],
    },
  });
  console.log(runId);
};

doAutomation();
```

## Steps to Reproduce the Problem

  1. Create a simple automation with one step using typescript API
  2. Notice the type errors while compiling

## Specifications

  - Version: 3.13.1
  - Platform: Node 16.14.0
  - Subsystem: Typescript 4.3.5

**Comment by tk26** [comment]
hey @manurana we've shipped a new version of the SDK with the support for the above feature! Let us know if you get a chance to try it out and/or if you have any feedback!
