### ISSUE TITLE
Support /users/:user_id/tokens

### ISSUE THREAD

**Issue by alexcroox** [trycourier/courier-node#99]
What's the best way to store push notification (FCM) tokens using the /users/:user_id/tokens/:token API?

I could make the raw API call myself but having both the SDK and raw API calls is a bit meh.

Does the SDK expose any kind of raw HTTP call function which auto attaches the bearer etc?

**Comment by drew-y** [comment]
> Does the SDK expose any kind of raw HTTP call function which auto attaches the bearer etc?

It does not currently expose this. I'll discuss with my teammates to see what there thoughts are on adding that.

In the meantime. I'll follow up with a quick update to add support for the tokens API.

**Comment by alexcroox** [comment]
Thanks! The convenience http raw function was only useful in the absence of SDK->API features. If you are adding support for tokens API then that’s great thanks

**Comment by drew-y** [comment]
Support added in v3.14.1

```ts
const { tokenManagement } = CourierClient({
    authorizationToken: "AUTH_TOKEN"
});

await tokenManagement.putUserTokens({
  user_id: "me",
  tokens: [{  token: "abc", provider_key: "apn" }]
});
```

**Comment by alexcroox** [comment]
Thank you so much!
